import { collection, addDoc } from 'firebase/firestore';
import { db, auth, handleFirestoreError, OperationType } from '../../firebase';
import { auditLogger, AuditActionType, AuditSeverity } from './AuditLogger';
import { promptRegistry, ModelConfig } from '../ai/promptRegistry';

/**
 * Interface representing a fully audited AI interaction per ISO 27001 & AI Governance standards.
 */
export interface AIAuditLog {
  id?: string;
  timestamp: string;               // ISO-8601 timestamp
  userId: string;                  // ID of user requesting AI inference
  userEmail: string;               // Email of user
  promptTemplateId: string;        // ID of prompt template (e.g. "tutor-conversation")
  promptVersion: string;           // Prompt version used (e.g. "1.2.0")
  compiledPrompt: string;          // Full prompt after variable interpolation
  systemInstruction?: string;      // System instruction given to the model
  userInput: string;               // Specific question or payload sent by user
  modelResponse: string;           // Response generated by the model
  modelName: string;               // e.g. "gemini-2.5-flash"
  modelConfig: ModelConfig;        // Temperature, tokens, etc.
  latencyMs: number;               // Model call duration in milliseconds
  status: 'SUCCESS' | 'FAILURE';   // Operation status
  error?: string;                  // Detailed error if status === FAILURE
  governanceControls: string[];    // Compliance frameworks satisfied
}

class AIAuditService {
  private collectionName = 'ai_usage_logs';

  /**
   * Records a complete AI transaction to Firestore and triggers the system AuditLogger mirror.
   * Promotes "explicability" and "auditability" for AI Governance.
   */
  public async logInteraction(params: {
    promptTemplateId: string;
    promptVersion: string;
    compiledPrompt: string;
    systemInstruction?: string;
    userInput: string;
    modelResponse: string;
    modelName: string;
    modelConfig: ModelConfig;
    latencyMs: number;
    status?: 'SUCCESS' | 'FAILURE';
    error?: string;
    userId?: string;
    userEmail?: string;
  }): Promise<string | null> {
    const currentUser = auth.currentUser;
    const userId = params.userId || currentUser?.uid || 'anonymous';
    const userEmail = params.userEmail || currentUser?.email || 'anonymous@lingolive.ai';
    const timestamp = new Date().toISOString();
    const status = params.status || 'SUCCESS';

    const auditLog: AIAuditLog = {
      timestamp,
      userId,
      userEmail,
      promptTemplateId: params.promptTemplateId,
      promptVersion: params.promptVersion,
      compiledPrompt: params.compiledPrompt,
      systemInstruction: params.systemInstruction,
      userInput: params.userInput,
      modelResponse: params.modelResponse,
      modelName: params.modelName,
      modelConfig: params.modelConfig,
      latencyMs: params.latencyMs,
      status,
      error: params.error,
      // Traceable controls for AI Governance, Accountability, and ISO 27001 Explicability rules
      governanceControls: ['ISO-27001-A.18.1.3', 'AI-EXPLICABILITY-TRACE', 'AI-GOVERNANCE-AUDIT'],
    };

    try {
      // 1. Direct local debug log
      console.log(
        `[AI-AUDIT] [${status}] Template: ${params.promptTemplateId} (v${params.promptVersion}) | Latency: ${params.latencyMs}ms | Model: ${params.modelName}`
      );

      // 2. Persist to Firestore ai_usage_logs (Write-Once Audit Trail)
      const docRef = await addDoc(collection(db, this.collectionName), auditLog);
      const logId = docRef.id;

      // 3. Mirror summary into the centralized Security Audit Trail via AuditLogger
      await auditLogger.log({
        action: AuditActionType.DATA_CREATE,
        description: `Registo de Utilização IA [ID: ${logId}] [Prompt: ${params.promptTemplateId} v${params.promptVersion}] [Latência: ${params.latencyMs}ms] [Status: ${status}]`,
        resource: {
          type: 'ai_usage_logs',
          id: logId,
          path: `${this.collectionName}/${logId}`,
        },
        severity: status === 'FAILURE' ? AuditSeverity.MEDIUM : AuditSeverity.INFO,
        status,
        failureReason: params.error,
        payloadSnippet: {
          promptTemplateId: params.promptTemplateId,
          promptVersion: params.promptVersion,
          modelName: params.modelName,
          latencyMs: params.latencyMs,
        },
        isoControls: ['A.12.4.1', 'A.18.1.3'],
      });

      return logId;
    } catch (error) {
      console.error('[AI-AUDIT-FATAL] Failed to write AI usage log to Firestore:', error);
      // Gracefully utilize the Firebase helper to log structural/permission diagnostic info
      try {
        handleFirestoreError(error, OperationType.CREATE, this.collectionName);
      } catch (e) {
        // Let it throw or log so the control panel or client can handle it
      }
      return null;
    }
  }

  /**
   * Helper to execute and automatically audit a general AI prompt operation.
   * Measures precise model latency and automatically grabs metadata from promptRegistry.
   */
  public async executeAndAudit<T>(
    promptTemplateId: string,
    variables: Record<string, string>,
    userInput: string,
    aiInferenceCall: (compiledPrompt: string, systemInstruction: string | undefined, config: ModelConfig) => Promise<T>
  ): Promise<{ result: T; latencyMs: number }> {
    const startTime = performance.now();
    let status: 'SUCCESS' | 'FAILURE' = 'SUCCESS';
    let errorMsg: string | undefined;
    let modelResponseStr = '';
    
    // 1. Compile prompt from promptRegistry
    const compiled = promptRegistry.compilePrompt(promptTemplateId, variables);

    try {
      // 2. Run the actual AI operation
      const result = await aiInferenceCall(compiled.content, compiled.systemInstruction, compiled.config);
      
      // Attempt to serialize the response for auditing
      modelResponseStr = typeof result === 'string' ? result : JSON.stringify(result);
      
      return { result, latencyMs: Math.round(performance.now() - startTime) };
    } catch (e: any) {
      status = 'FAILURE';
      errorMsg = e?.message || String(e);
      modelResponseStr = `ERROR: ${errorMsg}`;
      throw e;
    } finally {
      const latencyMs = Math.round(performance.now() - startTime);

      // 3. Automatically execute audit log run in the background
      this.logInteraction({
        promptTemplateId,
        promptVersion: promptRegistry.getTemplateById(promptTemplateId)?.activeVersion || '1.0.0',
        compiledPrompt: compiled.content,
        systemInstruction: compiled.systemInstruction,
        userInput,
        modelResponse: modelResponseStr,
        modelName: compiled.config.model,
        modelConfig: compiled.config,
        latencyMs,
        status,
        error: errorMsg,
      }).catch(err => {
        console.warn('[AI-AUDIT] Background logging failed:', err);
      });
    }
  }
}

export const aiAuditService = new AIAuditService();
