import React, { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { AnimatePresence, motion } from "motion/react";
import { BookOpen, Check, Library, Loader2, Plus, Search, ShoppingBag, Star, Store, X } from "lucide-react";
import { auth } from "../../firebase";
import { navigateToExternalCheckout } from "../../utils/navigationUtils";

type Section = "catalog" | "purchases" | "sell";
type ItemType = "course" | "material" | "live_class" | "service" | "subscription";
type Listing = { id:string; type:ItemType; title:string; description:string; category:string; language:string; price:number; currency:string; imageUrl:string|null; stockQuantity:number|null; sellerName:string; ratingAverage:number; ratingCount:number; salesCount:number };
type Purchase = { id:string; itemId:string; grantedAt:string; item:Listing|null };
const TYPE_LABELS:Record<ItemType,string>={course:"Curso",material:"Material",live_class:"Aula ao vivo",service:"Serviço",subscription:"Assinatura"};

async function request<T>(path:string, options:RequestInit={}):Promise<T>{
  if(!auth.currentUser) throw new Error("Inicie sessão para utilizar o marketplace.");
  const token=await auth.currentUser.getIdToken();
  const response=await fetch(`/api/marketplace${path}`,{...options,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`,...(options.headers||{})}});
  const body=await response.json().catch(()=>({}));
  if(!response.ok) throw new Error(body.message||body.error||"Não foi possível concluir a operação.");
  return body as T;
}

export const MarketplacePlatform:React.FC<{activeView?:string;setView?:(v:any)=>void}>=({activeView="marketplace"})=>{
  const [section,setSection]=useState<Section>(activeView==="marketplace-subscriptions"?"purchases":activeView==="marketplace-services"?"sell":"catalog");
  const [items,setItems]=useState<Listing[]>([]); const [purchases,setPurchases]=useState<Purchase[]>([]);
  const [query,setQuery]=useState(""); const [type,setType]=useState(""); const [loading,setLoading]=useState(true); const [busyId,setBusyId]=useState<string|null>(null); const [error,setError]=useState(""); const [notice,setNotice]=useState("");
  const loadCatalog=useCallback(async()=>{setLoading(true);setError("");try{const p=new URLSearchParams();if(query.trim())p.set("q",query.trim());if(type)p.set("type",type);setItems(await request<Listing[]>(`/items?${p}`));}catch(e:any){setError(e.message);}finally{setLoading(false);}},[query,type]);
  const loadPurchases=useCallback(async()=>{setLoading(true);setError("");try{setPurchases(await request<Purchase[]>("/purchases"));}catch(e:any){setError(e.message);}finally{setLoading(false);}},[]);
  useEffect(()=>{const timer=window.setTimeout(loadCatalog,250);return()=>window.clearTimeout(timer);},[loadCatalog]);
  useEffect(()=>{if(section==="purchases")void loadPurchases();},[section,loadPurchases]);
  const stats=useMemo(()=>({products:items.length,creators:new Set(items.map(i=>i.sellerName)).size,sales:items.reduce((s,i)=>s+i.salesCount,0)}),[items]);
  const checkout=async(item:Listing)=>{setBusyId(item.id);setError("");try{const result=await request<{url:string}>(`/items/${item.id}/checkout`,{method:"POST",body:"{}"});if(!result.url)throw new Error("Pagamento indisponível.");navigateToExternalCheckout(result.url);}catch(e:any){setError(e.message);setBusyId(null);}};
  return <main className="min-h-screen bg-slate-950 text-white pb-24">
    <header className="border-b border-white/10 bg-slate-950/90 backdrop-blur-xl sticky top-0 z-30"><div className="max-w-7xl mx-auto px-4 sm:px-6 py-4 flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-3"><div className="h-11 w-11 rounded-2xl bg-indigo-500 flex items-center justify-center"><Store size={22}/></div><div><h1 className="text-xl font-black">LingoLive Marketplace</h1><p className="text-xs text-slate-400">Conteúdos e serviços linguísticos verificados</p></div></div><nav className="flex gap-1 rounded-2xl bg-white/5 p-1" aria-label="Marketplace">{([["catalog","Explorar",ShoppingBag],["purchases","Minhas compras",Library],["sell","Publicar",Plus]] as const).map(([id,label,Icon])=><button key={id} onClick={()=>setSection(id)} className={`flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-bold transition ${section===id?"bg-indigo-500 text-white":"text-slate-400 hover:text-white hover:bg-white/5"}`}><Icon size={16}/>{label}</button>)}</nav></div></header>
    <div className="max-w-7xl mx-auto px-4 sm:px-6 pt-8">
      {(error||notice)&&<div className={`mb-6 flex items-center justify-between rounded-2xl border px-4 py-3 text-sm ${error?"border-rose-500/30 bg-rose-500/10 text-rose-200":"border-emerald-500/30 bg-emerald-500/10 text-emerald-200"}`}><span>{error||notice}</span><button onClick={()=>{setError("");setNotice("");}} aria-label="Fechar"><X size={16}/></button></div>}
      <AnimatePresence mode="wait">
        {section==="catalog"&&<motion.section key="catalog" initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0}}>
          <div className="grid lg:grid-cols-[1fr_auto] gap-8 items-end mb-8"><div><p className="text-cyan-400 font-bold text-sm mb-2">APRENDIZAGEM SEM FRONTEIRAS</p><h2 className="text-4xl sm:text-5xl font-black tracking-tight max-w-3xl">Encontre a próxima experiência para avançar no idioma.</h2></div><dl className="grid grid-cols-3 gap-5 text-center lg:border-l border-white/10 lg:pl-8"><div><dt className="text-xs text-slate-500">Ofertas</dt><dd className="text-2xl font-black">{stats.products}</dd></div><div><dt className="text-xs text-slate-500">Criadores</dt><dd className="text-2xl font-black">{stats.creators}</dd></div><div><dt className="text-xs text-slate-500">Vendas</dt><dd className="text-2xl font-black">{stats.sales}</dd></div></dl></div>
          <div className="flex flex-col sm:flex-row gap-3 mb-8"><label className="flex-1 flex items-center gap-3 bg-white/5 border border-white/10 rounded-2xl px-4 focus-within:border-indigo-400"><Search size={18} className="text-slate-500"/><input aria-label="Pesquisar marketplace" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquisar curso, material ou serviço" className="w-full bg-transparent py-3.5 outline-none placeholder:text-slate-600"/></label><select aria-label="Filtrar por tipo" value={type} onChange={e=>setType(e.target.value)} className="bg-slate-900 border border-white/10 rounded-2xl px-4 py-3.5 outline-none"><option value="">Todos os tipos</option>{Object.entries(TYPE_LABELS).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></div>
          {loading?<Loading/>:items.length===0?<Empty title="Ainda não existem ofertas publicadas" body="Criadores autorizados podem publicar a primeira oferta na área Publicar."/>:<div className="divide-y divide-white/10 border-y border-white/10">{items.map(item=><ListingRow key={item.id} item={item} busy={busyId===item.id} onBuy={()=>checkout(item)}/>)}</div>}
        </motion.section>}
        {section==="purchases"&&<motion.section key="purchases" initial={{opacity:0,y:8}} animate={{opacity:1,y:0}}><h2 className="text-3xl font-black mb-2">Minhas compras</h2><p className="text-slate-400 mb-8">Acesso concedido somente depois da confirmação do pagamento.</p>{loading?<Loading/>:purchases.length===0?<Empty title="Nenhuma compra confirmada" body="As aquisições aparecerão aqui após o webhook confirmar o pagamento."/>:<div className="divide-y divide-white/10 border-y border-white/10">{purchases.map(p=><div key={p.id} className="py-5 flex items-center gap-4"><Check className="text-emerald-400"/><div><h3 className="font-bold">{p.item?.title||"Oferta indisponível"}</h3><p className="text-sm text-slate-500">Acesso concedido em {new Date(p.grantedAt).toLocaleDateString()}</p></div></div>)}</div>}</motion.section>}
        {section==="sell"&&<CreateListing onCreated={item=>{setItems(current=>[item,...current]);setNotice("Oferta publicada com sucesso.");setSection("catalog");}} onError={setError}/>}
      </AnimatePresence>
    </div>
  </main>;
};

const ListingRow:React.FC<{item:Listing;busy:boolean;onBuy:()=>void}>=({item,busy,onBuy})=><article className="py-6 grid sm:grid-cols-[auto_1fr_auto] gap-5 items-center group"><div className="w-16 h-16 rounded-2xl bg-indigo-500/10 text-indigo-300 flex items-center justify-center"><BookOpen/></div><div><div className="flex flex-wrap items-center gap-2 mb-1"><span className="text-xs font-bold text-cyan-400">{TYPE_LABELS[item.type]}</span><span className="text-xs text-slate-600">{item.language.toUpperCase()}</span></div><h3 className="text-lg font-black group-hover:text-indigo-300 transition">{item.title}</h3><p className="text-sm text-slate-400 line-clamp-2 max-w-2xl">{item.description}</p><div className="flex gap-4 mt-2 text-xs text-slate-500"><span>{item.sellerName}</span><span className="flex gap-1 items-center"><Star size={12} className="text-amber-400"/>{item.ratingAverage||"Novo"} ({item.ratingCount})</span></div></div><div className="sm:text-right"><p className="text-xl font-black mb-2">{new Intl.NumberFormat("pt-PT",{style:"currency",currency:item.currency}).format(item.price)}</p><button onClick={onBuy} disabled={busy} className="min-w-32 rounded-xl bg-indigo-500 hover:bg-indigo-400 disabled:opacity-50 px-4 py-2.5 font-bold text-sm">{busy?<Loader2 className="animate-spin mx-auto" size={18}/>:item.type==="live_class"?"Reservar":"Comprar"}</button></div></article>;

const CreateListing=({onCreated,onError}:{onCreated:(item:Listing)=>void;onError:(m:string)=>void})=>{const[saving,setSaving]=useState(false);const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving(true);onError("");const data=new FormData(e.currentTarget);try{onCreated(await request<Listing>("/items",{method:"POST",body:JSON.stringify(Object.fromEntries(data))}));}catch(err:any){onError(err.message);}finally{setSaving(false);}};return <motion.section key="sell" initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="max-w-3xl"><h2 className="text-3xl font-black mb-2">Publicar oferta</h2><p className="text-slate-400 mb-8">Disponível para administradores, organizações e professores autorizados.</p><form onSubmit={submit} className="grid sm:grid-cols-2 gap-4">{[["title","Título"],["category","Categoria"],["language","Idioma (ex.: pt, en)"],["price","Preço"]].map(([name,label])=><label key={name} className="text-sm font-bold text-slate-300">{label}<input name={name} required type={name==="price"?"number":"text"} min={name==="price"?"0.5":undefined} step={name==="price"?"0.01":undefined} className="mt-2 w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 outline-none focus:border-indigo-400"/></label>)}<label className="text-sm font-bold text-slate-300">Tipo<select name="type" className="mt-2 w-full bg-slate-900 border border-white/10 rounded-xl px-4 py-3">{Object.entries(TYPE_LABELS).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label className="text-sm font-bold text-slate-300">Moeda<select name="currency" className="mt-2 w-full bg-slate-900 border border-white/10 rounded-xl px-4 py-3">{["USD","EUR","AOA","BRL","GBP"].map(c=><option key={c}>{c}</option>)}</select></label><label className="sm:col-span-2 text-sm font-bold text-slate-300">Descrição<textarea name="description" required minLength={20} maxLength={4000} rows={6} className="mt-2 w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 outline-none focus:border-indigo-400"/></label><button disabled={saving} className="sm:col-span-2 rounded-xl bg-indigo-500 hover:bg-indigo-400 disabled:opacity-50 px-5 py-3.5 font-black">{saving?"A publicar…":"Publicar oferta"}</button></form></motion.section>;};
const Loading=()=> <div className="py-24 flex justify-center"><Loader2 className="animate-spin text-indigo-400"/></div>;
const Empty=({title,body}:{title:string;body:string})=> <div className="py-24 border-y border-white/10 text-center"><ShoppingBag className="mx-auto text-slate-700 mb-4" size={42}/><h3 className="text-xl font-black">{title}</h3><p className="text-slate-500 mt-2">{body}</p></div>;
