import React, { useCallback, useEffect, useMemo, useState } from "react";
import { BookOpen, Library, Loader2, PackagePlus, Search, Send, ShoppingBag, Store } from "lucide-react";
import { marketplaceService, MarketplaceEntitlementDto, MarketplaceItemDto } from "../../services/marketplace.service";
type Section = "catalog" | "library" | "creator";
const sectionForView = (view: string): Section => view === "marketplace-subscriptions" ? "library" : ["marketplace-services", "marketplace-analytics", "marketplace-lars"].includes(view) ? "creator" : "catalog";
const Empty = ({title,text}:{title:string;text:string}) => <div className="bg-white border border-dashed rounded-2xl py-16 px-6 text-center"><h2 className="font-black text-lg">{title}</h2><p className="text-sm text-slate-500 mt-2">{text}</p></div>;

export const MarketplacePlatform: React.FC<{ activeView?: string; setView?: (view: any) => void }> = ({ activeView = "marketplace" }) => {
  const [section, setSection] = useState<Section>(() => sectionForView(activeView));
  const [items, setItems] = useState<MarketplaceItemDto[]>([]); const [library, setLibrary] = useState<MarketplaceEntitlementDto[]>([]); const [creatorItems, setCreatorItems] = useState<MarketplaceItemDto[]>([]);
  const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const [draft, setDraft] = useState({ title: "", description: "", itemType: "COURSE", language: "", cefrLevel: "A1", priceCoins: 0, stockQuantity: null as number | null, contentRef: "" });
  const load = useCallback(async () => { setLoading(true); setError(""); try { if (section === "catalog") setItems(await marketplaceService.catalog()); else if (section === "library") setLibrary(await marketplaceService.library()); else setCreatorItems(await marketplaceService.creatorItems()); } catch (e) { setError(e instanceof Error ? e.message : "Não foi possível carregar o Marketplace."); } finally { setLoading(false); } }, [section]);
  useEffect(() => setSection(sectionForView(activeView)), [activeView]); useEffect(() => { void load(); }, [load]);
  const filtered = useMemo(() => items.filter(item => `${item.title} ${item.language} ${item.cefrLevel}`.toLowerCase().includes(query.toLowerCase())), [items, query]);
  const acquire = async (id: string) => { setNotice(""); setError(""); try { await marketplaceService.acquire(id); setNotice("Aquisição concluída. O conteúdo está na sua biblioteca."); } catch (e) { setError(e instanceof Error ? e.message : "Aquisição falhou."); } };
  const create = async (event: React.FormEvent) => { event.preventDefault(); setError(""); try { await marketplaceService.createItem(draft); setNotice("Rascunho criado com dados reais."); setDraft({ title: "", description: "", itemType: "COURSE", language: "", cefrLevel: "A1", priceCoins: 0, stockQuantity: null, contentRef: "" }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Não foi possível criar o produto."); } };
  return <main className="min-h-screen bg-slate-50 py-8"><div className="max-w-7xl mx-auto px-4 space-y-6">
    <header className="flex items-center gap-3"><div className="p-3 rounded-2xl bg-indigo-100 text-indigo-700"><Store /></div><div><h1 className="text-3xl font-black">Marketplace LingoLIVE</h1><p className="text-slate-500">Conteúdos pedagógicos adquiridos com Lingo Coins.</p></div></header>
    <nav aria-label="Áreas do Marketplace" className="flex gap-2 overflow-x-auto">{([['catalog','Catálogo',ShoppingBag],['library','Minha biblioteca',Library],['creator','Área do criador',PackagePlus]] as const).map(([id,label,Icon]) => <button key={id} aria-current={section === id ? "page" : undefined} onClick={() => setSection(id)} className={`flex items-center gap-2 px-4 py-3 rounded-xl font-bold ${section === id ? "bg-indigo-600 text-white" : "bg-white border"}`}><Icon className="w-4 h-4" />{label}</button>)}</nav>
    {notice ? <div role="status" className="p-4 rounded-xl bg-emerald-50 border border-emerald-200 text-emerald-800">{notice}</div> : null}{error ? <div role="alert" className="p-4 rounded-xl bg-rose-50 border border-rose-200 text-rose-800">{error}<button onClick={load} className="ml-3 underline font-bold">Tentar novamente</button></div> : null}
    {loading ? <div className="py-20 flex justify-center" aria-label="A carregar"><Loader2 className="animate-spin" /></div> : section === "catalog" ? <section className="space-y-5"><label className="relative block max-w-xl"><Search className="absolute left-4 top-3.5 w-5 h-5 text-slate-400"/><span className="sr-only">Pesquisar catálogo</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquisar por título, idioma ou nível" className="w-full pl-12 pr-4 py-3 rounded-xl border bg-white"/></label>{filtered.length === 0 ? <Empty title="Nenhum conteúdo publicado" text="Apenas produtos reais aprovados pela moderação aparecem aqui."/> : <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">{filtered.map(item=><article key={item.id} className="bg-white border rounded-2xl p-5 space-y-3"><div className="flex justify-between text-xs font-bold"><span>{item.itemType}</span><span>{item.cefrLevel}</span></div><h2 className="font-black text-lg">{item.title}</h2><p className="text-sm text-slate-600 line-clamp-3">{item.description}</p><p className="text-xs text-slate-500">{item.language} · {item.creatorName}</p><button onClick={()=>acquire(item.id)} className="w-full py-3 rounded-xl bg-indigo-600 text-white font-bold">Adquirir por {item.priceCoins} moedas</button></article>)}</div>}</section>
    : section === "library" ? <section>{library.length === 0 ? <Empty title="A sua biblioteca está vazia" text="Os conteúdos adquiridos aparecerão aqui após concessão pelo servidor."/> : <div className="grid md:grid-cols-2 gap-4">{library.map(entry=><article key={entry.id} className="bg-white border rounded-2xl p-5"><BookOpen className="text-indigo-600 mb-3"/><h2 className="font-bold">{entry.title}</h2><p className="text-sm text-slate-500">Acesso {entry.status.toLowerCase()} · {new Date(entry.grantedAt).toLocaleDateString()}</p></article>)}</div>}</section>
    : <section className="grid lg:grid-cols-2 gap-6"><form onSubmit={create} className="bg-white border rounded-2xl p-6 space-y-3"><h2 className="font-black text-xl">Novo conteúdo</h2><input required minLength={3} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="Título" className="w-full p-3 border rounded-xl"/><textarea required minLength={20} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="Descrição pedagógica" className="w-full p-3 border rounded-xl"/><div className="grid grid-cols-2 gap-3"><input required value={draft.language} onChange={e=>setDraft({...draft,language:e.target.value})} placeholder="Idioma" className="p-3 border rounded-xl"/><select value={draft.cefrLevel} onChange={e=>setDraft({...draft,cefrLevel:e.target.value})} className="p-3 border rounded-xl">{["A1","A2","B1","B2","C1","C2"].map(x=><option key={x}>{x}</option>)}</select></div><input required value={draft.contentRef} onChange={e=>setDraft({...draft,contentRef:e.target.value})} placeholder="Referência do conteúdo existente" className="w-full p-3 border rounded-xl"/><input aria-label="Preço em moedas" type="number" min="0" max="1000000" value={draft.priceCoins} onChange={e=>setDraft({...draft,priceCoins:Number(e.target.value)})} className="w-full p-3 border rounded-xl"/><button className="w-full py-3 bg-indigo-600 text-white font-bold rounded-xl">Guardar rascunho</button></form><div className="space-y-3"><h2 className="font-black text-xl">Os meus produtos</h2>{creatorItems.length === 0 ? <Empty title="Nenhum produto criado" text="Nada será publicado sem moderação."/> : creatorItems.map(item=><article key={item.id} className="bg-white border rounded-2xl p-4 flex justify-between gap-4"><div><h3 className="font-bold">{item.title}</h3><p className="text-xs text-slate-500">{item.status}{item.rejectionReason ? ` · ${item.rejectionReason}` : ""}</p></div>{["DRAFT","REJECTED"].includes(item.status) ? <button onClick={async()=>{await marketplaceService.submitItem(item.id);await load();}} className="flex items-center gap-1 text-indigo-700 font-bold"><Send className="w-4 h-4"/>Revisão</button>:null}</article>)}</div></section>}
  </div></main>;
};
