import { describe, expect, it, vi } from 'vitest';
import { RegionalExpressionEngine, resolveRegionalLanguageProfile } from './index';
import { buildTutorGeoContext, protectRegionalExpressions } from './integration';
const entry = { expression: 'bué', language: 'pt', variants: ['pt-AO'], regions: ['Angola'], meaning: 'muito', standardEquivalent: 'muito', register: 'slang' as const }; const profile = resolveRegionalLanguageProfile({ selectedLanguage: 'pt', country: 'AO' });
describe('Tutor Geo integration', () => {
  it('builds variant-aware context without asserting identity from location', () => { const context = buildTutorGeoContext({ selectedLanguage: 'pt', country: 'AO' }); expect(context.profile.variant).toBe('pt-AO'); expect(context.instruction).toContain('Never infer identity from location'); });
  it('protects a known expression in the active variant', async () => { const engine = new RegionalExpressionEngine([entry]); const corrections = await protectRegionalExpressions({ text: 'Isso é bué bom', profile, engine, corrections: [{ original: 'bué', replacement: 'muito' }, { original: 'bom', replacement: 'ótimo' }] }); expect(corrections).toEqual([{ original: 'bom', replacement: 'ótimo' }]); });
  it('does not suppress a correction when expression is known only for another variant', async () => { const engine = new RegionalExpressionEngine([{ ...entry, variants: ['pt-PT'] }]); const correction = { original: 'bué', replacement: 'muito' }; expect(await protectRegionalExpressions({ text: 'bué', profile, engine, corrections: [correction] })).toEqual([correction]); });
  it('does not suppress a larger correction span', async () => { const engine = new RegionalExpressionEngine([entry]); const correction = { original: 'é bué bom', replacement: 'é muito bom' }; expect(await protectRegionalExpressions({ text: 'Isso é bué bom', profile, engine, corrections: [correction] })).toEqual([correction]); });
  it('emits privacy-preserving telemetry', async () => { const emit = vi.fn(); const engine = new RegionalExpressionEngine([entry]); await protectRegionalExpressions({ text: 'bué', profile, engine, corrections: [], telemetry: { emit } }); const payload = emit.mock.calls[0][1]; expect(payload).toMatchObject({ languageVariant: 'pt-AO', register: 'slang', expectedVariant: true }); expect(payload).not.toHaveProperty('text'); expect(payload).not.toHaveProperty('expression'); });
  it('keeps correction flow operational when telemetry fails', async () => { const engine = new RegionalExpressionEngine([entry]); const corrections = [{ original: 'bom', replacement: 'ótimo' }]; await expect(protectRegionalExpressions({ text: 'bué bom', profile, engine, corrections, telemetry: { emit: async () => { throw new Error('telemetry unavailable'); } } })).resolves.toEqual(corrections); });
});
