import { describe, expect, it, vi } from 'vitest';
import { attachGeoLinguisticCorrectionPipeline, GeoAwareTutorPipeline } from './tutor-pipeline';
describe('GeoAwareTutorPipeline', () => {
  it('injects regional context and protects active regionalisms after generic correction', async () => { const correct = vi.fn().mockResolvedValue([{ original: 'bué', replacement: 'muito' }, { original: 'bom', replacement: 'ótimo' }]); const pipeline = new GeoAwareTutorPipeline({ correct }); const result = await pipeline.correct({ selectedLanguage: 'pt', country: 'AO', learnerText: 'Isso é bué bom' }); expect(correct).toHaveBeenCalledWith(expect.objectContaining({ learnerText: 'Isso é bué bom', systemInstructions: [expect.stringContaining('pt-AO')] })); expect(result).toEqual([{ original: 'bom', replacement: 'ótimo' }]); });
  it('honors explicit learner variant over country inference', async () => { const correct = vi.fn().mockResolvedValue([{ original: 'legal', replacement: 'bom' }]); const pipeline = new GeoAwareTutorPipeline({ correct }); const result = await pipeline.correct({ selectedLanguage: 'pt', explicitVariant: 'pt-BR', country: 'AO', learnerText: 'Isso é legal' }); expect(result).toEqual([]); expect(correct.mock.calls[0][0].systemInstructions[0]).toContain('pt-BR'); });
  it('does not allow telemetry failure to break corrections', async () => { const pipeline = new GeoAwareTutorPipeline({ correct: async () => [{ original: 'bom', replacement: 'ótimo' }] }, { emit: async () => { throw new Error('offline'); } }); await expect(pipeline.correct({ selectedLanguage: 'pt', country: 'AO', learnerText: 'bué bom' })).resolves.toEqual([{ original: 'bom', replacement: 'ótimo' }]); });
  it('wraps existing orchestrator while preserving its instance', async () => { const original = vi.fn().mockResolvedValue([{ original: 'bué', replacement: 'muito' }, { original: 'bom', replacement: 'ótimo' }]); const orchestrator = { correctLearnerText: original, route: () => 'kept' }; const wired = attachGeoLinguisticCorrectionPipeline(orchestrator); expect(wired).toBe(orchestrator); expect(wired.route()).toBe('kept'); await expect(wired.correctLearnerText({ selectedLanguage: 'pt', country: 'AO', learnerText: 'bué bom' })).resolves.toEqual([{ original: 'bom', replacement: 'ótimo' }]); expect(original).toHaveBeenCalledOnce(); expect(original.mock.calls[0][0].geoSystemInstructions[0]).toContain('pt-AO'); });
  it('does not double-wrap the orchestrator', async () => { const original = vi.fn().mockResolvedValue([{ original: 'bué', replacement: 'muito' }]); const orchestrator = { correctLearnerText: original }; attachGeoLinguisticCorrectionPipeline(orchestrator); attachGeoLinguisticCorrectionPipeline(orchestrator); await expect(orchestrator.correctLearnerText({ selectedLanguage: 'pt', country: 'AO', learnerText: 'bué' })).resolves.toEqual([]); expect(original).toHaveBeenCalledOnce(); expect(original.mock.calls[0][0].geoSystemInstructions).toHaveLength(1); });
});
